# Generated by Django 3.2 on 2021-07-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='title')),
                ('price', models.FloatField()),
                ('count', models.IntegerField()),
                ('tempereture', models.FloatField(default=20.0)),
            ],
        ),
    ]
